[build]
  command = "CI= npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# ✅ Keep only sitemap (removed html-validate plugin)
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
