# Netlify config for Create React App + Netlify Functions
[build]
  command = "npm ci && npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Optional, but keep it simple for now (no HTML validator)
[[plugins]]
  package = "@netlify/plugin-sitemap"
