# ===== PLUGIN CONFIGURATION =====
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-html-validate"

# ===== BUILD CONFIGURATION =====
[build]
  command = "CI= npm run build"
  publish = "build"

# ===== FUNCTIONS CONFIGURATION =====
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# ===== REDIRECTS CONFIGURATION =====
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
