# Static site + Functions (no HTML validator plugin)
[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Optional: keep sitemap plugin only (safe)
[[plugins]]
  package = "@netlify/plugin-sitemap"
